name: bicep-workflow

on:
  workflow_dispatch:
    
  push:
    branches:
      - staging
      - main
  
  pull_request:
    branches:
      - staging
      - main

# https://github.com/actions/runner/issues/480
# cannot use directly in reusable workflows
env:
  REGION: eastus
  SCOPE: subscription

#checking concurrency
concurrency: ${{ github.ref }}

jobs:

  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: View github context
  #       run: echo '${{ toJSON(github) }}'

  lint:
    uses: ./.github/workflows/lint.yml
      
  preflight-validation-dev:
    uses: ./.github/workflows/preflight-validation.yml
    needs: lint
    # if: ${{ github.event_name == 'pull_request'}}
    with:
      environment: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
    
  deploy-dev:
    # if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/deploy.yml
    needs: preflight-validation-dev
    with:
      environment: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}

  preflight-validation-staging:
    uses: ./.github/workflows/preflight-validation.yml
    needs: lint
    with:
      environment: staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}

  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    needs: preflight-validation-staging
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main')}}
    with:
      environment: staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}

  preflight-validation-prod:
    uses: ./.github/workflows/preflight-validation.yml
    if: ${{ github.base_ref == 'main' || github.ref_name == 'main' }}
    needs: lint
    with:
      environment: prod
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
  
  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    needs: preflight-validation-prod
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    with:
      environment: prod
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
 
  # test:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #   - name: Run Test Against APIM
  #     run: echo TESTING

  # rollback:
  #   runs-on: ubuntu-latest
  #   needs: test