apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugwebapi
spec:
  selector:
    matchLabels:
      app: debugwebapi
  replicas: 1 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: debugwebapi
    spec:
      containers:
        - name: debugwebapi
          image: [ACR_NAME].azurecr.io/debugwebapiaks:latest
          resources:
            limits:
              memory: 2058Mi
              cpu: "700m"
            requests:
              memory: 512Mi
              cpu: "50m"
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: debugwebapi-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
    - targetPort: 443
      name: port443
      port: 443
      protocol: TCP
  selector:
    app: debugwebapi