adx_displayorder: 3
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: Product B (sample)
adx_pagetemplateid: 60559fba-d1b3-4b64-ab9b-cbd6a1294ca1
adx_parentpageid: 4e5f61f6-a476-4e81-b69b-e4c3a30bc7ab
adx_partialurl: product-b-deleted
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_rootwebpageid: 9ae15591-50d6-4ce8-8885-68b943b7e03d
adx_sharedpageconfiguration: false
adx_title: Product B (sample)
adx_webpageid: e1e609ad-384a-49ed-b4b2-b60f81fa2dcd
adx_webpagelanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
statecode: 1
statuscode: 2
